### ISSUE TITLE
Support linux

### ISSUE THREAD

**Issue by josephwinston** [YoussefKababe/pgquick#1]
Any problems with running this on linux too?

**Comment by YoussefKababe** [comment]
Hello @josephwinston! I have released builds for Linux too, have you given them a try?

https://github.com/YoussefKababe/pgquick/releases/tag/v0.1.0

I haven't done much testing on other systems, but I will do asap! Let me know if it doesn't work.

**Comment by josephwinston** [comment]
Excellent.  Please close.  My error came from:

```
$ npm install
npm error code EBADPLATFORM
npm error notsup Unsupported platform for appdmg@0.6.6: wanted {"os":"darwin"} (current: {"os":"linux"})
npm error notsup Valid os:  darwin
npm error notsup Actual os: linux
npm error A complete log of this run can be found in: /home/josephwinston/.npm/_logs/2024-09-11T20_43_51_904Z-debug-0.log```
